from dataclasses import dataclass
from enum import Enum

class StringMatchMode(str, Enum):
    CONTAINS: str
    STARTS_WITH: str
    ENDS_WITH: str
    REGEX: str
    EQUALS: str

@dataclass(frozen=True)
class StringMatcher:
    value: str
    mode: StringMatchMode = ...
    ignore_case: bool = ...

@dataclass(frozen=True)
class ClassMatcher:
    descriptor: str | None = ...
    name: StringMatcher | None = ...
    source_file: StringMatcher | None = ...
    modifiers: int | None = ...
    super_class: str | None = ...
    interfaces: list[str] = ...
    using_strings: list[StringMatcher] = ...
    search_packages: list[str] = ...
    exclude_packages: list[str] = ...
    ignore_packages_case: bool = ...
    fields: list[FieldMatcher] = ...
    methods: list[MethodMatcher] = ...
    all_of: list[ClassMatcher] = ...
    any_of: list[ClassMatcher] = ...
    none_of: list[ClassMatcher] = ...

@dataclass(frozen=True)
class MethodMatcher:
    descriptor: str | None = ...
    name: StringMatcher | None = ...
    modifiers: int | None = ...
    declared_class: str | None = ...
    return_type: str | None = ...
    parameter_types: list[str | None] | None = ...
    parameter_count: int | None = ...
    proto_shorty: str | None = ...
    op_codes: list[int] = ...
    op_names: list[str] = ...
    using_strings: list[StringMatcher] = ...
    using_numbers: list[int | float] = ...
    using_fields: list[str] = ...
    invoked_methods: list[str] = ...
    caller_methods: list[str] = ...
    search_packages: list[str] = ...
    exclude_packages: list[str] = ...
    ignore_packages_case: bool = ...
    all_of: list[MethodMatcher] = ...
    any_of: list[MethodMatcher] = ...
    none_of: list[MethodMatcher] = ...

@dataclass(frozen=True)
class FieldMatcher:
    descriptor: str | None = ...
    name: StringMatcher | None = ...
    modifiers: int | None = ...
    declared_class: str | None = ...
    type: str | None = ...
    search_packages: list[str] = ...
    exclude_packages: list[str] = ...
    ignore_packages_case: bool = ...
    read_methods: list[MethodMatcher] = ...
    write_methods: list[MethodMatcher] = ...
    all_of: list[FieldMatcher] = ...
    any_of: list[FieldMatcher] = ...
    none_of: list[FieldMatcher] = ...

def contains(value: str, *, ignore_case: bool = False) -> StringMatcher: ...
def starts_with(value: str, *, ignore_case: bool = False) -> StringMatcher: ...
def ends_with(value: str, *, ignore_case: bool = False) -> StringMatcher: ...
def regex(value: str, *, ignore_case: bool = False) -> StringMatcher: ...
def eq(value: str, *, ignore_case: bool = False) -> StringMatcher: ...
