import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Compiles the committed extensions.lock into Kotlin constants (ExtensionLock.kt)
 * so the module body pins extension-pack versions and SHA-256 hashes at compile
 * time. The device downloads only these pinned assets and rejects anything whose
 * hash does not match — a replaced Release asset can never be loaded.
 */
abstract class GenerateExtensionLockTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val lockFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val namespace: Property<String>

    @get:Input
    abstract val baseUrl: Property<String>

    @TaskAction
    fun generate() {
        val packs = LockParser.parse(lockFile.get().asFile.readText())
        val scriptDeps = packs.pack("script-deps")
            ?: error("extensions.lock is missing pack 'script-deps'")
        val cloudflared = packs.pack("cloudflared")
            ?: error("extensions.lock is missing pack 'cloudflared'")

        val outputFile = outputDir.get().asFile
            .resolve("${namespace.get().replace(".", "/")}/extensions/ExtensionLock.kt")
        outputFile.parentFile.mkdirs()
        outputFile.writeText(render(scriptDeps, cloudflared))
        logger.lifecycle("ExtensionLock.kt generated (script-deps {}, cloudflared {})",
            scriptDeps.version, cloudflared.version)
    }

    private fun List<LockParser.ParsedPack>.pack(id: String) = firstOrNull { it.id == id }

    private fun LockParser.ParsedPack.assetName(): String {
        val (name, _) = files.entries.single()
        val stem = name.substringBeforeLast('.')
        val ext = name.substringAfterLast('.', "")
        return "$stem-$version.$ext"
    }

    private fun render(s: LockParser.ParsedPack, c: LockParser.ParsedPack): String = buildString {
        append("// Generated by GenerateExtensionLockTask from extensions.lock. Do not edit manually.\n")
        append("package ${namespace.get()}.extensions\n\n")
        append("object ExtensionLock {\n")
        append("    const val BASE_URL = \"${baseUrl.get()}\"\n\n")
        append("    object ScriptDeps {\n")
        append("        const val ID = \"script-deps\"\n")
        append("        const val VERSION = \"${s.version}\"\n")
        append("        const val SHA256 = \"${s.files.getValue("script-deps.dex")}\"\n")
        append("        const val ASSET_NAME = \"${s.assetName()}\"\n")
        append("    }\n\n")
        append("    object Cloudflared {\n")
        append("        const val ID = \"cloudflared\"\n")
        append("        const val VERSION = \"${c.version}\"\n")
        append("        const val SHA256 = \"${c.files.getValue("cloudflared.zip")}\"\n")
        append("        const val ASSET_NAME = \"${c.assetName()}\"\n")
        append("    }\n")
        append("}\n")
    }
}

/**
 * Minimal parser for the machine-written extensions.lock. The file is produced by
 * `cargo xtask extensions lock --write` (serde_json pretty output), so the shape is
 * stable; a full JSON parser is not warranted here.
 */
internal object LockParser {

    data class ParsedPack(
        val id: String,
        val version: String,
        val files: Map<String, String>,
    )

    private val packRegex = Regex(
        """\{\s*"id":\s*"([^"]+)",\s*"version":\s*"([^"]+)",\s*"files":\s*\{(.*?)\}\s*\}""",
        RegexOption.DOT_MATCHES_ALL,
    )
    private val fileRegex = Regex(""""([^"]+)":\s*"([0-9a-fA-F]{64})"""")

    fun parse(content: String): List<ParsedPack> = packRegex.findAll(content).map { match ->
        val (id, version, filesBody) = match.destructured
        ParsedPack(
            id = id,
            version = version,
            files = fileRegex.findAll(filesBody).associate { it.groupValues[1] to it.groupValues[2] },
        )
    }.toList()
}
