// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769045345140

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0x8573E805, 0x5D6560FB, 0x6E867C98 };