// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769069415185

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0xB197EFC1, 0xE51E2202, 0x43BCB974 };